/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacy;
import com.mysql.jdbc.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A-jay
 */
public class AddEmployee extends javax.swing.JFrame {
Connection con1;
        PreparedStatement insert;
        String user;
        String pass;
    /**
     * Creates new form AddPatient
     */
    public AddEmployee() {
         this.setLocation(500, 250);
        this.setVisible(true);
        initComponents();
        user = Singleton.getInstance().getUser();
        pass = Singleton.getInstance().getPass();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        textEmployeeSalary = new javax.swing.JTextField();
        textEmployeeAddress = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        textEmployeeName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        buttonEmployeeAdd = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        textEmployeePharm = new javax.swing.JTextField();
        textEmployeePhone = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        textEmployeeJoining = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green_background.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel17.setText("Employee");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("Salary");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        textEmployeeSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmployeeSalaryActionPerformed(evt);
            }
        });
        getContentPane().add(textEmployeeSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 56, -1));

        textEmployeeAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmployeeAddressActionPerformed(evt);
            }
        });
        getContentPane().add(textEmployeeAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 58, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("Address");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        textEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmployeeNameActionPerformed(evt);
            }
        });
        getContentPane().add(textEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 58, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Name");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        buttonEmployeeAdd.setText("Add");
        buttonEmployeeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEmployeeAddActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEmployeeAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("Pharm Id");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        textEmployeePharm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmployeePharmActionPerformed(evt);
            }
        });
        getContentPane().add(textEmployeePharm, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 58, -1));

        textEmployeePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmployeePhoneActionPerformed(evt);
            }
        });
        getContentPane().add(textEmployeePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 58, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setText("Phone no");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel23.setText("Joining Date");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        textEmployeeJoining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmployeeJoiningActionPerformed(evt);
            }
        });
        getContentPane().add(textEmployeeJoining, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 58, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue_background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 400, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textEmployeeSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmployeeSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmployeeSalaryActionPerformed

    private void textEmployeeAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmployeeAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmployeeAddressActionPerformed

    private void textEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmployeeNameActionPerformed

    private void buttonEmployeeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEmployeeAddActionPerformed
        String name = textEmployeeName.getText().trim();
        int pharm = Integer.parseInt(textEmployeePharm.getText().trim());
        int salary = Integer.parseInt(textEmployeeSalary.getText().trim());
        String address = textEmployeeAddress.getText().trim();
        String phone = textEmployeePhone.getText().trim();
        java.sql.Date date = java.sql.Date.valueOf(textEmployeeJoining.getText().trim());

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy",user,pass);

            insert = con1.prepareStatement("insert into employee(emp_name,pharm_id,salary,address,phone_no,joining_date) values(?,?,?,?,?,?)");
            //insert.setInt(1, id);
            insert.setString(1, name);
            insert.setInt(2, pharm);
            insert.setInt(3, salary);
            insert.setString(4, address);
            insert.setString(5,phone);
            insert.setDate(6, date);
            insert.executeUpdate();

            JOptionPane.showMessageDialog(this, "Success insertion");
            textEmployeeName.setText("");
            textEmployeePharm.setText("");
            textEmployeeSalary.setText("");
            textEmployeeAddress.setText("");
            textEmployeePhone.setText("");
            textEmployeeJoining.setText("");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }//GEN-LAST:event_buttonEmployeeAddActionPerformed

    private void textEmployeePharmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmployeePharmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmployeePharmActionPerformed

    private void textEmployeePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmployeePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmployeePhoneActionPerformed

    private void textEmployeeJoiningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmployeeJoiningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmployeeJoiningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEmployeeAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JTextField textEmployeeAddress;
    private javax.swing.JTextField textEmployeeJoining;
    private javax.swing.JTextField textEmployeeName;
    private javax.swing.JTextField textEmployeePharm;
    private javax.swing.JTextField textEmployeePhone;
    private javax.swing.JTextField textEmployeeSalary;
    // End of variables declaration//GEN-END:variables
}
