/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacy;
import com.mysql.jdbc.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A-jay
 */
public class AddPatient extends javax.swing.JFrame {
Connection con1;
        PreparedStatement insert;
    private final String pass;
    private final String user;
    /**
     * Creates new form AddPatient
     */
    public AddPatient() {
         this.setLocation(500, 250);
        this.setVisible(true);
        initComponents();
        user = Singleton.getInstance().getUser();
        pass = Singleton.getInstance().getPass();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        textPatientAge = new javax.swing.JTextField();
        textPatientAddress = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        textpatientName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        buttonPatientAdd = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        textPatientGender = new javax.swing.JTextField();
        textPatientPhone = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel17.setText("Patient");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 41, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("age");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 198, -1, -1));

        textPatientAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPatientAgeActionPerformed(evt);
            }
        });
        getContentPane().add(textPatientAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 221, 56, -1));

        textPatientAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPatientAddressActionPerformed(evt);
            }
        });
        getContentPane().add(textPatientAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 221, 58, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("Address");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 198, -1, -1));

        textpatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpatientNameActionPerformed(evt);
            }
        });
        getContentPane().add(textpatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 132, 58, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Patient Name");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 109, -1, -1));

        buttonPatientAdd.setText("Add");
        buttonPatientAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPatientAddActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPatientAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("gender(m/f/t)");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 109, -1, -1));

        textPatientGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPatientGenderActionPerformed(evt);
            }
        });
        getContentPane().add(textPatientGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 132, 58, -1));

        textPatientPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPatientPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(textPatientPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 298, 58, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setText("Phone no");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 275, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue_background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 580, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPatientAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPatientAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPatientAgeActionPerformed

    private void textPatientAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPatientAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPatientAddressActionPerformed

    private void textpatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpatientNameActionPerformed

    private void buttonPatientAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPatientAddActionPerformed
        String name = textpatientName.getText().trim();
        String gender = textPatientGender.getText().trim();
        int age = Integer.parseInt(textPatientAge.getText().trim());
        String address = textPatientAddress.getText().trim();
        String phone = textPatientPhone.getText().trim();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy",user,pass);

            insert = con1.prepareStatement("insert into patient(name,gender,address,age,phone_no) values(?,?,?,?,?)");
            //insert.setInt(1, id);
            insert.setString(1, name);
            insert.setString(2, gender);
            insert.setString(3, address);
            insert.setInt(4,age);
            insert.setString(5, phone);
            insert.executeUpdate();

            JOptionPane.showMessageDialog(this, "Success insertion");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }//GEN-LAST:event_buttonPatientAddActionPerformed

    private void textPatientGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPatientGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPatientGenderActionPerformed

    private void textPatientPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPatientPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPatientPhoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPatientAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JTextField textPatientAddress;
    private javax.swing.JTextField textPatientAge;
    private javax.swing.JTextField textPatientGender;
    private javax.swing.JTextField textPatientPhone;
    private javax.swing.JTextField textpatientName;
    // End of variables declaration//GEN-END:variables
}
