/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacy;

import com.mysql.jdbc.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A-jay
 */
public class AddSells extends javax.swing.JFrame {

    /**
     * Creates new form AddSelles
     */
    Connection con1;
        PreparedStatement insert;
    private final String pass;
    private final String user;
    public AddSells() {
         this.setLocation(500, 250);
        this.setVisible(true);
        initComponents();
        user = Singleton.getInstance().getUser();
        pass = Singleton.getInstance().getPass();
        SetPharmacyData2();
        SetMedicineData();
    }
public void SetPharmacyData2(){
        int c=0;
      try {
            //Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy",user,pass);
            
            insert = con1.prepareStatement("select * from pharmacy");
            
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData rss = (ResultSetMetaData) rs.getMetaData();
            c = rss.getColumnCount();
            
            DefaultTableModel model = (DefaultTableModel) tablePharmacySells.getModel();
            model.setRowCount(0);
            
            while(rs.next()){
                Vector v2 = new Vector();
                //for(int i=0;i<c;i++){
                    v2.add(rs.getInt("pharm_id"));
                    v2.add(rs.getString("name"));
                    v2.add(rs.getString("address"));
                    v2.add(rs.getString("phone_no"));
                //}
                model.addRow(v2);
            }
           
        } /*catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        }*/ catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
       
        }
    }
    
    public void SetMedicineData(){
        int c;
      try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy",user,pass);
            
            insert = con1.prepareStatement("select * from medicine");
            
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData rss = (ResultSetMetaData) rs.getMetaData();
            c = rss.getColumnCount();
            
            DefaultTableModel model = (DefaultTableModel) tableMedicineSells.getModel();
            model.setRowCount(0);
            
            while(rs.next()){
                Vector v2 = new Vector();
                for(int i=0;i<c;i++){
                    v2.add(rs.getInt("mid"));
                    v2.add(rs.getString("med_name"));
                    v2.add(rs.getInt("price"));
                    v2.add(rs.getDate("exp_date"));
                }
                model.addRow(v2);
            }
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
       
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textSellsQuantity = new javax.swing.JTextField();
        textSellsMid = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        buttonAddSells = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        textSellsPharm = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePharmacySells = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableMedicineSells = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel3.setText("Sells");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 22, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Quantity");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 350, -1, -1));

        textSellsQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSellsQuantityActionPerformed(evt);
            }
        });
        getContentPane().add(textSellsQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 373, 56, -1));

        textSellsMid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSellsMidActionPerformed(evt);
            }
        });
        getContentPane().add(textSellsMid, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 287, 56, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel24.setText("MID");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 264, -1, -1));

        buttonAddSells.setText("Add");
        buttonAddSells.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddSellsActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAddSells, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 411, -1, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setText("Pharm Id");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 264, -1, -1));

        textSellsPharm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSellsPharmActionPerformed(evt);
            }
        });
        getContentPane().add(textSellsPharm, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 287, 56, -1));

        tablePharmacySells.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pharm_id", "Name", "Address", "Phone_no"
            }
        ));
        jScrollPane3.setViewportView(tablePharmacySells);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 113, 193, 89));

        tableMedicineSells.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MID", "Med Name", "price", "exp_date"
            }
        ));
        jScrollPane4.setViewportView(tableMedicineSells);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 113, 193, 89));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel23.setText("Pharmacy");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel26.setText("Medicine");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 90, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue_background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 430, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textSellsQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSellsQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSellsQuantityActionPerformed

    private void textSellsMidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSellsMidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSellsMidActionPerformed

    private void buttonAddSellsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddSellsActionPerformed
        int mid = Integer.parseInt(textSellsMid.getText().trim());
        int pharm_id = Integer.parseInt(textSellsPharm.getText().trim());
        int qnt = Integer.parseInt(textSellsQuantity.getText().trim());

        try {
            
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy",user,pass);

            insert = con1.prepareStatement("select quantity from sells where mid=? and pharm_id=?");
            insert.setInt(1, mid);
            insert.setInt(2, pharm_id);
            ResultSet rs =insert.executeQuery();
            if(rs.next()){
                int val = rs.getInt("quantity");
                insert = con1.prepareStatement("update sells set quantity =? where mid=? and pharm_id = ?");
                insert.setInt(1, val+qnt);
                insert.setInt(2, mid);
                insert.setInt(3, pharm_id);
                insert.executeUpdate();
            }else{

                insert = con1.prepareStatement("insert into sells(mid,pharm_id,quantity) values(?,?,?)");
                insert.setInt(1, mid);
                insert.setInt(2, pharm_id);
                insert.setInt(3, qnt);
                insert.executeUpdate();
            }
            JOptionPane.showMessageDialog(this, "Success insertion");
        } catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }//GEN-LAST:event_buttonAddSellsActionPerformed

    private void textSellsPharmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSellsPharmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSellsPharmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSells().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddSells;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tableMedicineSells;
    private javax.swing.JTable tablePharmacySells;
    private javax.swing.JTextField textSellsMid;
    private javax.swing.JTextField textSellsPharm;
    private javax.swing.JTextField textSellsQuantity;
    // End of variables declaration//GEN-END:variables
}
