/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacy;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A-jay
 */
public class ExecuteBill extends javax.swing.JFrame {
Connection con1;
        PreparedStatement insert;
    private String pass;
    private String user;
    /**
     * Creates new form ExecuteBill
     */
    public ExecuteBill(int bid,int pid) {
         this();
        user = Singleton.getInstance().getUser();
        pass = Singleton.getInstance().getPass();
        ExecuteBill(bid,pid);
    }
     public ExecuteBill() {
          this.setLocation(500, 250);
        this.setVisible(true);
        initComponents();
       // ExecuteBill(bid,pid);
    }
    
     private void ExecuteBill(int bid,int pid){
        textPidBillTotal.setText(String.valueOf(pid));
        try {
            //Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy",user,pass);
            
            insert = con1.prepareStatement("select name from patient where pid=?");
            insert.setInt(1, pid);
            ResultSet rs1 = insert.executeQuery();
            if(rs1.next()){ 
                textNameBillTotal.setText(rs1.getString("name"));   
            }
            insert = con1.prepareStatement("select amount from bill where pid=? and bid=?");
            insert.setInt(1, pid);
            insert.setInt(2, bid);
            ResultSet rs2 = insert.executeQuery();
            if(rs2.next()){
                textTotalBillTotal.setText(rs2.getString("amount"));
            }
            
            DefaultTableModel model = (DefaultTableModel) tableTotalBill.getModel();
            model.setRowCount(0);
            insert = con1.prepareStatement("SELECT medicine.med_name,medicine.price,med_on_bill.quantiy from medicine,med_on_bill where medicine.mid = med_on_bill.mid and med_on_bill.bid=?");
            insert.setInt(1, bid);
            ResultSet rs = insert.executeQuery();
            while(rs.next()){
                Vector v = new Vector();
                v.add(rs.getString("med_name"));
                v.add(rs.getString("price"));
                v.add(rs.getInt("quantiy"));
                model.addRow(v);
            }
            
            
            
        //JOptionPane.showMessageDialog(this, "Success insertion");
        } /*catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        }*/ catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        tableTotalBill = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        pharmacyNameTag1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        textNameBillTotal = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        textPidBillTotal = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        textTotalBillTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableTotalBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Med_Name", "Price", "qnt"
            }
        ));
        jScrollPane6.setViewportView(tableTotalBill);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 239, 325, 91));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel28.setText("Medicines");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 216, -1, -1));

        pharmacyNameTag1.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        pharmacyNameTag1.setText("Bill Total");
        getContentPane().add(pharmacyNameTag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 27, -1, -1));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel27.setText("Patient Name:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        textNameBillTotal.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        textNameBillTotal.setText("name");
        getContentPane().add(textNameBillTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel30.setText("Patient Id:");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 139, -1, -1));

        textPidBillTotal.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        textPidBillTotal.setText("id");
        getContentPane().add(textPidBillTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 132, -1, -1));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel31.setText("bill Total:");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 377, -1, -1));

        textTotalBillTotal.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        textTotalBillTotal.setText("total");
        getContentPane().add(textTotalBillTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 370, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue_background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 430, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExecuteBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExecuteBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExecuteBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExecuteBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExecuteBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel pharmacyNameTag1;
    private javax.swing.JTable tableTotalBill;
    private javax.swing.JLabel textNameBillTotal;
    private javax.swing.JLabel textPidBillTotal;
    private javax.swing.JLabel textTotalBillTotal;
    // End of variables declaration//GEN-END:variables
}
