/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacy;

import com.mysql.jdbc.ResultSetMetaData;
import java.awt.Dimension;
import java.sql.Connection;

import java.sql.DriverManager;
import java.sql.PreparedStatement;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author A-jay
 */
public class Pharmacy extends javax.swing.JFrame {
        Connection con1;
        PreparedStatement insert;
    /**
     * Creates new form Pharmacy
     */
    public Pharmacy() {
        
               
                //panel6.setVisible(false);
                //panel7.setVisible(false);
                
        initComponents();
         MainPanel.setVisible(true);
        panel3.setVisible(false);
        panel4.setVisible(false);
        panel5.setVisible(false);
        panel6.setVisible(false);
        
        panel7.setVisible(false);
        panel8.setVisible(false);
        panel9.setVisible(false);
        panel10.setVisible(false);
    }
    
    public void AllClear(){
        MainPanel.setVisible(true);
        panel3.setVisible(false);
        panel4.setVisible(false);
        panel5.setVisible(false);
        panel6.setVisible(false);
        
        panel7.setVisible(false);
        panel8.setVisible(false);
        panel9.setVisible(false);
        panel10.setVisible(false);
        set.clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        buttonMainAddItems = new javax.swing.JButton();
        buttonMainPharmacy = new javax.swing.JButton();
        billDetailsMain = new javax.swing.JButton();
        buttonEmployeeDetails = new javax.swing.JButton();
        BillDetailPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        billTable = new javax.swing.JTable();
        labelBillNotFound = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonPharmacy = new javax.swing.JButton();
        buttonMedicine = new javax.swing.JButton();
        buttonPatient = new javax.swing.JButton();
        buttonSells = new javax.swing.JButton();
        panel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textPhAddress = new javax.swing.JTextField();
        textPhPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textPhName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        panel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textSellsQuantity = new javax.swing.JTextField();
        textSellsMid = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        buttonAddSells = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        textSellsPharm = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePharmacySells = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableMedicineSells = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        panel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textMedPrice = new javax.swing.JTextField();
        textMedExp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textMedName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        buttonMedAdd = new javax.swing.JButton();
        panel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        textPatientAge = new javax.swing.JTextField();
        textPatientAddress = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        textpatientName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        buttonPatientAdd = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        textPatientGender = new javax.swing.JTextField();
        textPatientPhone = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        panel6 = new javax.swing.JPanel();
        dropPharmacyName = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        buttonOkPharmacyName = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        panel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDrugCatalog = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCart = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        buttonAddItem = new javax.swing.JButton();
        buttonCheckOut = new javax.swing.JButton();
        patientIdCart = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        pharmacyNameTag = new javax.swing.JLabel();
        textQuantityDrugCatalog = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        panel10 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableTotalBill = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        pharmacyNameTag1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        textNameBillTotal = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        textPidBillTotal = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        textTotalBillTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonMainAddItems.setText("Add Items");
        buttonMainAddItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMainAddItemsActionPerformed(evt);
            }
        });

        buttonMainPharmacy.setText("Pharmacy");
        buttonMainPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMainPharmacyActionPerformed(evt);
            }
        });

        billDetailsMain.setText("Bill Details");
        billDetailsMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billDetailsMainActionPerformed(evt);
            }
        });

        buttonEmployeeDetails.setText("Employee Details");
        buttonEmployeeDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEmployeeDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(billDetailsMain)
                    .addComponent(buttonMainAddItems))
                .addGap(67, 67, 67)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonMainPharmacy)
                    .addComponent(buttonEmployeeDetails))
                .addGap(82, 82, 82))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMainPharmacy)
                    .addComponent(buttonMainAddItems))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billDetailsMain)
                    .addComponent(buttonEmployeeDetails))
                .addGap(37, 37, 37))
        );

        billTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(billTable);

        labelBillNotFound.setForeground(new java.awt.Color(255, 0, 51));
        labelBillNotFound.setText("No bill found for Entered BillNumber");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel32.setText("Enter Bill No.");

        jLabel33.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel33.setText("Check Bill Info");

        javax.swing.GroupLayout BillDetailPanelLayout = new javax.swing.GroupLayout(BillDetailPanel);
        BillDetailPanel.setLayout(BillDetailPanelLayout);
        BillDetailPanelLayout.setHorizontalGroup(
            BillDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BillDetailPanelLayout.createSequentialGroup()
                .addGroup(BillDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BillDetailPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BillDetailPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel33))
                    .addGroup(BillDetailPanelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(BillDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBillNotFound)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BillDetailPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BillDetailPanelLayout.setVerticalGroup(
            BillDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BillDetailPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BillDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelBillNotFound)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel1.setText("Select to Add");
        jLabel1.setName(""); // NOI18N

        buttonPharmacy.setText("Pharmacy");
        buttonPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPharmacyActionPerformed(evt);
            }
        });

        buttonMedicine.setText("Medicine");
        buttonMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMedicineActionPerformed(evt);
            }
        });

        buttonPatient.setText("Patient");
        buttonPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPatientActionPerformed(evt);
            }
        });

        buttonSells.setText("Sells");
        buttonSells.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSellsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPharmacy)
                    .addComponent(buttonPatient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonMedicine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSells, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPharmacy)
                    .addComponent(buttonMedicine))
                .addGap(37, 37, 37)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPatient)
                    .addComponent(buttonSells))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel2.setText("Pharmacy");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Address");

        textPhAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPhAddressActionPerformed(evt);
            }
        });

        textPhPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPhPhoneActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Phone no.");

        textPhName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPhNameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Name");

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPhAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(textPhName, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(textPhPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButton2))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(45, 45, 45)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPhName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPhAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPhPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(30, 30, 30))
        );

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel3.setText("Sells");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Quantity");

        textSellsQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSellsQuantityActionPerformed(evt);
            }
        });

        textSellsMid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSellsMidActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel24.setText("MID");

        buttonAddSells.setText("Add");
        buttonAddSells.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddSellsActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setText("Pharm Id");

        textSellsPharm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSellsPharmActionPerformed(evt);
            }
        });

        tablePharmacySells.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pharm_id", "Name", "Address", "Phone_no"
            }
        ));
        jScrollPane3.setViewportView(tablePharmacySells);

        tableMedicineSells.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MID", "Med Name", "price", "exp_date"
            }
        ));
        jScrollPane4.setViewportView(tableMedicineSells);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel23.setText("Pharmacy");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel26.setText("Medicine");

        javax.swing.GroupLayout panel9Layout = new javax.swing.GroupLayout(panel9);
        panel9.setLayout(panel9Layout);
        panel9Layout.setHorizontalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel9Layout.createSequentialGroup()
                .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel9Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textSellsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel24)
                            .addComponent(textSellsMid, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(textSellsPharm, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23)
                        .addGap(169, 169, 169)
                        .addComponent(jLabel26))
                    .addGroup(panel9Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonAddSells)
                .addGap(161, 161, 161))
        );
        panel9Layout.setVerticalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel9Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textSellsMid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel9Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textSellsPharm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSellsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAddSells)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel8.setText("Medicine");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Price");

        textMedPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMedPriceActionPerformed(evt);
            }
        });

        textMedExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMedExpActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("exp_date(yyyy-mm-dd)");

        textMedName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMedNameActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Med Name");

        buttonMedAdd.setText("Add");
        buttonMedAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMedAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel5Layout.createSequentialGroup()
                                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(textMedPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(44, 44, 44)
                                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(textMedExp, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(textMedName, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(buttonMedAdd))
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGap(42, 42, 42)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textMedName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textMedPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textMedExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addComponent(buttonMedAdd)
                .addContainerGap())
        );

        jLabel17.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel17.setText("Patient");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("age");

        textPatientAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPatientAgeActionPerformed(evt);
            }
        });

        textPatientAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPatientAddressActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("Address");

        textpatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpatientNameActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Patient Name");

        buttonPatientAdd.setText("Add");
        buttonPatientAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPatientAddActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("gender(m/f/t)");

        textPatientGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPatientGenderActionPerformed(evt);
            }
        });

        textPatientPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPatientPhoneActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setText("Phone no");

        javax.swing.GroupLayout panel8Layout = new javax.swing.GroupLayout(panel8);
        panel8.setLayout(panel8Layout);
        panel8Layout.setHorizontalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel8Layout.createSequentialGroup()
                .addGroup(panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel8Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(buttonPatientAdd))
                    .addGroup(panel8Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17)
                                .addGroup(panel8Layout.createSequentialGroup()
                                    .addGroup(panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel22)
                                        .addComponent(textPatientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(120, 120, 120)))
                            .addGroup(panel8Layout.createSequentialGroup()
                                .addGroup(panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(textPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addComponent(textpatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(textPatientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)
                                    .addComponent(textPatientGender, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(45, 45, 45))
        );
        panel8Layout.setVerticalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel8Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel17)
                .addGap(31, 31, 31)
                .addGroup(panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel8Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textpatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel8Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPatientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel8Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPatientGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPatientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(buttonPatientAdd)
                .addGap(30, 30, 30))
        );

        dropPharmacyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropPharmacyNameActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Pharmacy Name");

        buttonOkPharmacyName.setText("Ok");
        buttonOkPharmacyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkPharmacyNameActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel29.setText("Select Pharmacy");

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(dropPharmacyName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)))
                    .addGroup(panel6Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(buttonOkPharmacyName)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel29)
                .addGap(36, 36, 36)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dropPharmacyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(buttonOkPharmacyName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableDrugCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MID", "Med_Name", "Price", "qnt"
            }
        ));
        jScrollPane1.setViewportView(tableDrugCatalog);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Pharmacy Drug Catalog");

        tableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MID", "Med_Name", "Price", "qnt"
            }
        ));
        jScrollPane2.setViewportView(tableCart);
        if (tableCart.getColumnModel().getColumnCount() > 0) {
            tableCart.getColumnModel().getColumn(3).setHeaderValue("qnt\\");
            }

            jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
            jLabel14.setText("Item in cart");

            buttonAddItem.setText("Add Item");
            buttonAddItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonAddItemActionPerformed(evt);
                }
            });

            buttonCheckOut.setText("Check Out");
            buttonCheckOut.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonCheckOutActionPerformed(evt);
                }
            });

            patientIdCart.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    patientIdCartActionPerformed(evt);
                }
            });

            jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel15.setText("Enter PID :");

            pharmacyNameTag.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
            pharmacyNameTag.setText("Pharmacy Name");

            textQuantityDrugCatalog.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    textQuantityDrugCatalogActionPerformed(evt);
                }
            });

            jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel16.setText("QNT :");

            javax.swing.GroupLayout panel7Layout = new javax.swing.GroupLayout(panel7);
            panel7.setLayout(panel7Layout);
            panel7Layout.setHorizontalGroup(
                panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel7Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(textQuantityDrugCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(buttonAddItem)
                    .addGap(103, 103, 103))
                .addGroup(panel7Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pharmacyNameTag)
                        .addGroup(panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panel7Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(patientIdCart, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCheckOut))
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            panel7Layout.setVerticalGroup(
                panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel7Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(pharmacyNameTag)
                    .addGap(45, 45, 45)
                    .addComponent(jLabel13)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panel7Layout.createSequentialGroup()
                            .addGroup(panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttonAddItem)
                                .addComponent(textQuantityDrugCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16))
                            .addGap(30, 30, 30)
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(buttonCheckOut))
                        .addGroup(panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patientIdCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            tableTotalBill.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Med_Name", "Price", "qnt"
                }
            ));
            jScrollPane6.setViewportView(tableTotalBill);

            jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
            jLabel28.setText("Medicines");

            pharmacyNameTag1.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
            pharmacyNameTag1.setText("Bill Total");

            jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
            jLabel27.setText("Patient Name:");

            textNameBillTotal.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
            textNameBillTotal.setText("name");

            jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
            jLabel30.setText("Patient Id:");

            textPidBillTotal.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
            textPidBillTotal.setText("id");

            jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
            jLabel31.setText("bill Total:");

            textTotalBillTotal.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
            textTotalBillTotal.setText("total");

            javax.swing.GroupLayout panel10Layout = new javax.swing.GroupLayout(panel10);
            panel10.setLayout(panel10Layout);
            panel10Layout.setHorizontalGroup(
                panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel10Layout.createSequentialGroup()
                    .addGroup(panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel10Layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(jLabel27)
                            .addGap(18, 18, 18)
                            .addComponent(textNameBillTotal)
                            .addGap(67, 67, 67)
                            .addComponent(jLabel30)
                            .addGap(18, 18, 18)
                            .addComponent(textPidBillTotal))
                        .addGroup(panel10Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(panel10Layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addComponent(jLabel31)
                            .addGap(18, 18, 18)
                            .addComponent(textTotalBillTotal))
                        .addGroup(panel10Layout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(pharmacyNameTag1)))
                    .addContainerGap(124, Short.MAX_VALUE))
            );
            panel10Layout.setVerticalGroup(
                panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel10Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(pharmacyNameTag1)
                    .addGap(56, 56, 56)
                    .addGroup(panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(textNameBillTotal)
                        .addComponent(jLabel30)
                        .addComponent(textPidBillTotal))
                    .addGap(58, 58, 58)
                    .addComponent(jLabel28)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(40, 40, 40)
                    .addGroup(panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(textTotalBillTotal))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BillDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(panel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BillDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void buttonPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPharmacyActionPerformed
        panel3.setVisible(false);
        panel4.setVisible(true);
    }//GEN-LAST:event_buttonPharmacyActionPerformed

    private void buttonMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMedicineActionPerformed
        panel3.setVisible(false);
        panel5.setVisible(true);
    }//GEN-LAST:event_buttonMedicineActionPerformed

    private void textPhAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPhAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPhAddressActionPerformed

    private void textPhPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPhPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPhPhoneActionPerformed

    private void textPhNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPhNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPhNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //int id = Integer.parseInt(textPhId.getText().trim());
        String name = textPhName.getText().trim();
        String phoneno = textPhPhone.getText().trim();
        String address = textPhAddress.getText().trim();
        
         try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy","root","");

            insert = con1.prepareStatement("insert into pharmacy(name,address,phone_no) values(?,?,?)");
            //insert.setInt(1, id);
            insert.setString(1, name);
            insert.setString(2, address);
            insert.setString(3,phoneno);
            insert.executeUpdate();
            
        JOptionPane.showMessageDialog(this, "Success insertion");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textMedPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMedPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMedPriceActionPerformed

    private void textMedExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMedExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMedExpActionPerformed

    private void textMedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMedNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMedNameActionPerformed

    private void buttonMedAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMedAddActionPerformed
       // int id = Integer.parseInt(textMedMID.getText().trim());
        String name = textMedName.getText().trim();
        int price = Integer.parseInt(textMedPrice.getText().trim());
        java.sql.Date date = java.sql.Date.valueOf(textMedExp.getText().trim());
        
         try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy","root","");

            insert = con1.prepareStatement("insert into medicine(med_name,price,exp_date) values(?,?,?)");
            //insert.setInt(1, id);
            insert.setString(1, name);
            insert.setInt(2, price);
            insert.setDate(3,date);
            insert.executeUpdate();
            
        JOptionPane.showMessageDialog(this, "Success insertion");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }//GEN-LAST:event_buttonMedAddActionPerformed

    private void dropPharmacyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropPharmacyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropPharmacyNameActionPerformed

    private void buttonOkPharmacyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkPharmacyNameActionPerformed
        MainPanel.setVisible(false);
        panel3.setVisible(false);
        panel4.setVisible(false);
        panel5.setVisible(false);
        panel6.setVisible(false);
        if(dropPharmacyName.getSelectedItem()!=null){
        DefaultTableModel model = (DefaultTableModel) tableCart.getModel();
            model.setRowCount(0);
        SetPharmacyData();
        }
    }//GEN-LAST:event_buttonOkPharmacyNameActionPerformed
      
    public void SetPharmacyData(){
        String pharmacyName = dropPharmacyName.getSelectedItem().toString();
         pharmacyNameTag.setText(pharmacyName);
          int c;
      try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy","root","");
            insert = con1.prepareStatement("select * from pharmacy where name=?");
             insert.setString(1, pharmacyName);
             //System.out.println(insert.toString());
            ResultSet rs1 = insert.executeQuery();
            int pharm_id = 0;
            if(rs1.next())pharm_id=rs1.getInt("pharm_id");
            insert = con1.prepareStatement("select medicine.mid,medicine.med_name,medicine.price,sells.quantity from medicine,sells where sells.pharm_id=? and sells.mid = medicine.mid");
            insert.setInt(1, pharm_id);
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData rss = (ResultSetMetaData) rs.getMetaData();
            c = rss.getColumnCount();
            
            DefaultTableModel model = (DefaultTableModel) tableDrugCatalog.getModel();
            model.setRowCount(0);
            
            while(rs.next()){
                Vector v2 = new Vector();
                for(int i=0;i<c;i++){
                    v2.add(rs.getInt("mid"));
                    v2.add(rs.getString("med_name"));
                    v2.add(rs.getInt("price"));
                    v2.add(rs.getInt("quantity"));
                }
                model.addRow(v2);
            }
           
            panel7.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            panel6.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
            panel6.setVisible(true);
        }
    }
    
    private void buttonMainPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMainPharmacyActionPerformed
        MainPanel.setVisible(false);
        panel3.setVisible(false);
        panel4.setVisible(false);
        panel5.setVisible(false);
       // panel6.setVisible(true);
        new SelectPharmacy().setVisible(true);
        PharmacySelect();
    }//GEN-LAST:event_buttonMainPharmacyActionPerformed

    private void patientIdCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIdCartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIdCartActionPerformed
   HashMap<Integer,Integer> set = new HashMap<>();
    private void buttonAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddItemActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableCart.getModel();
        int row = tableDrugCatalog.getSelectedRow();
        int mid = Integer.parseInt(tableDrugCatalog.getModel().getValueAt(row, 0).toString().trim());
        System.out.println(mid);
        String med_name = tableDrugCatalog.getModel().getValueAt(row, 1).toString();
        int price = Integer.parseInt(tableDrugCatalog.getModel().getValueAt(row, 2).toString());
        int qnt = Integer.parseInt(tableDrugCatalog.getModel().getValueAt(row, 3).toString());
        int drugqnt = Integer.parseInt(textQuantityDrugCatalog.getText().toString());
        if(set.get(mid)!=null){
            int tempqnt = set.get(mid);
            if(tempqnt+drugqnt>qnt){
                JOptionPane.showMessageDialog(this, "Quantity Exceed");
                return;
            }else{
                set.put(mid,tempqnt+drugqnt);
                Vector v = new Vector();
                v.add(mid);
                v.add(med_name);
                v.add(price);
                v.add(drugqnt+tempqnt);
            }
            int c = tableCart.getRowCount();
            for(int i=0;i<c;i++){
                if(Integer.parseInt(tableCart.getModel().getValueAt(i, 0).toString())==mid){
                    tableCart.getModel().setValueAt(tempqnt+drugqnt,i, 3);
                }
            }
        }else{
            if(drugqnt>qnt){
                JOptionPane.showMessageDialog(this, "Quantity Exceed");
                return;
            }
            set.put(mid,drugqnt);
                Vector v = new Vector();
                v.add(mid);
                v.add(med_name);
                v.add(price);
                v.add(drugqnt);
                model.addRow(v);
        }
    }//GEN-LAST:event_buttonAddItemActionPerformed

    private void textQuantityDrugCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQuantityDrugCatalogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQuantityDrugCatalogActionPerformed

    private void buttonMainAddItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMainAddItemsActionPerformed
        new AddItem().setVisible(true);
        setVisible(false);
        MainPanel.setVisible(false);
        panel3.setVisible(true);
    }//GEN-LAST:event_buttonMainAddItemsActionPerformed

    private void textPatientAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPatientAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPatientAgeActionPerformed

    private void textPatientAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPatientAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPatientAddressActionPerformed

    private void textpatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpatientNameActionPerformed

    private void buttonPatientAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPatientAddActionPerformed
        String name = textpatientName.getText().trim();
        String gender = textPatientGender.getText().trim();
        int age = Integer.parseInt(textPatientAge.getText().trim());
        String address = textPatientAddress.getText().trim();
        String phone = textPatientPhone.getText().trim();
        
        
         try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy","root","");

            insert = con1.prepareStatement("insert into patient(name,gender,address,age,phone_no) values(?,?,?,?,?)");
            //insert.setInt(1, id);
            insert.setString(1, name);
            insert.setString(2, gender);
            insert.setString(3, address);
            insert.setInt(4,age);
            insert.setString(5, phone);
            insert.executeUpdate();
            
        JOptionPane.showMessageDialog(this, "Success insertion");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }//GEN-LAST:event_buttonPatientAddActionPerformed

    private void textPatientGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPatientGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPatientGenderActionPerformed

    private void buttonPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPatientActionPerformed
        panel3.setVisible(false);
        panel8.setVisible(true);
    }//GEN-LAST:event_buttonPatientActionPerformed

    private void textPatientPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPatientPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPatientPhoneActionPerformed

    private void buttonCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCheckOutActionPerformed
       if(patientIdCart.getText().toString().trim().length()==0){
           JOptionPane.showMessageDialog(this, "Please Enter PID");
           return;
       }
        int pid = Integer.parseInt(patientIdCart.getText().toString().trim());
        
       int val = tableCart.getRowCount();
       int sum=0;
       for(int i=0;i<val;i++){
           int qnt = Integer.parseInt(tableCart.getModel().getValueAt(i, 3).toString().trim());
           int price = Integer.parseInt(tableCart.getModel().getValueAt(i, 2).toString().trim());
           sum+=qnt*price;
       }
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy","root","");

            String pharmacyName = dropPharmacyName.getSelectedItem().toString();
            insert = con1.prepareStatement("select * from pharmacy where name=?");
             insert.setString(1, pharmacyName);
            ResultSet rs1 = insert.executeQuery();
            int pharm_id = 0;
            if(rs1.next())pharm_id=rs1.getInt("pharm_id");
            
            insert = con1.prepareStatement("insert into bill(amount,pid,pharm_id) values(?,?,?)");
            //insert.setInt(1, id);
            insert.setInt(1, sum);
            insert.setInt(2, pid);
            insert.setInt(3,pharm_id);
            insert.executeUpdate();
            
            insert = con1.prepareStatement("select * from bill order by bid desc limit 1");
            ResultSet rs = insert.executeQuery();
            int bid =0;
            if(rs.next()){
                bid = rs.getInt("bid");
            }
            
            
            for(int i=0;i<val;i++){
                int qnt = Integer.parseInt(tableCart.getModel().getValueAt(i, 3).toString().trim());
           int mid = Integer.parseInt(tableCart.getModel().getValueAt(i, 0).toString().trim());
           
           insert = con1.prepareStatement("insert into med_on_bill(bid,mid,quantiy)values(?,?,?)");
           insert.setInt(1, bid);
           insert.setInt(2, mid);
           insert.setInt(3, qnt);
           insert.executeUpdate();
           System.out.print(qnt);
           insert = con1.prepareStatement("update sells set quantity =(select sum(quantity) from sells where mid=? and pharm_id= ?)-? where mid=? and pharm_id =?");
           insert.setInt(1,mid);
           insert.setInt(2,pharm_id);
           insert.setInt(3,qnt);
           insert.setInt(4,mid);
           insert.setInt(5,pharm_id); 
           insert.executeUpdate();
           
       }
            
            ExecuteBill(bid,pid);
            panel7.setVisible(false);
            panel10.setVisible(true);
        JOptionPane.showMessageDialog(this, "Success Bill");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
        } catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
        }
        
        
       
    }//GEN-LAST:event_buttonCheckOutActionPerformed

    private void ExecuteBill(int bid,int pid){
        textPidBillTotal.setText(String.valueOf(pid));
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy","root","");
            
            insert = con1.prepareStatement("select name from patient where pid=?");
            insert.setInt(1, pid);
            ResultSet rs1 = insert.executeQuery();
            if(rs1.next()){ 
                textNameBillTotal.setText(rs1.getString("name"));   
            }
            insert = con1.prepareStatement("select amount from bill where pid=? and bid=?");
            insert.setInt(1, pid);
            insert.setInt(2, bid);
            ResultSet rs2 = insert.executeQuery();
            if(rs2.next()){
                textTotalBillTotal.setText(rs2.getString("amount"));
            }
            
            DefaultTableModel model = (DefaultTableModel) tableTotalBill.getModel();
            model.setRowCount(0);
            insert = con1.prepareStatement("SELECT medicine.med_name,medicine.price,med_on_bill.quantiy from medicine,med_on_bill where medicine.mid = med_on_bill.mid and med_on_bill.bid=?");
            insert.setInt(1, bid);
            ResultSet rs = insert.executeQuery();
            while(rs.next()){
                Vector v = new Vector();
                v.add(rs.getString("med_name"));
                v.add(rs.getString("price"));
                v.add(rs.getInt("quantiy"));
                model.addRow(v);
            }
            
            
            
        JOptionPane.showMessageDialog(this, "Success insertion");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }
    
    private void buttonSellsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSellsActionPerformed
        panel3.setVisible(false);
        panel9.setVisible(true);
        SetPharmacyData2();
        SetMedicineData();
    }//GEN-LAST:event_buttonSellsActionPerformed

    public void SetPharmacyData2(){
        int c;
      try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy","root","");
            
            insert = con1.prepareStatement("select * from pharmacy");
            
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData rss = (ResultSetMetaData) rs.getMetaData();
            c = rss.getColumnCount();
            
            DefaultTableModel model = (DefaultTableModel) tablePharmacySells.getModel();
            model.setRowCount(0);
            
            while(rs.next()){
                Vector v2 = new Vector();
                //for(int i=0;i<c;i++){
                    v2.add(rs.getInt("pharm_id"));
                    v2.add(rs.getString("name"));
                    v2.add(rs.getString("address"));
                    v2.add(rs.getString("phone_no"));
                //}
                model.addRow(v2);
            }
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
       
        }
    }
    
    public void SetMedicineData(){
        int c;
      try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy","root","");
            
            insert = con1.prepareStatement("select * from medicine");
            
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData rss = (ResultSetMetaData) rs.getMetaData();
            c = rss.getColumnCount();
            
            DefaultTableModel model = (DefaultTableModel) tableMedicineSells.getModel();
            model.setRowCount(0);
            
            while(rs.next()){
                Vector v2 = new Vector();
                for(int i=0;i<c;i++){
                    v2.add(rs.getInt("mid"));
                    v2.add(rs.getString("med_name"));
                    v2.add(rs.getInt("price"));
                    v2.add(rs.getDate("exp_date"));
                }
                model.addRow(v2);
            }
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
       
        }
    }
    
    private void textSellsQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSellsQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSellsQuantityActionPerformed

    private void textSellsMidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSellsMidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSellsMidActionPerformed

    private void buttonAddSellsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddSellsActionPerformed
        int mid = Integer.parseInt(textSellsMid.getText().trim());
        int pharm_id = Integer.parseInt(textSellsPharm.getText().trim());
        int qnt = Integer.parseInt(textSellsQuantity.getText().trim());
        
         try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy","root","");

            insert = con1.prepareStatement("select quantity from sells where mid=? and pharm_id=?");
            insert.setInt(1, mid);
            insert.setInt(2, pharm_id);
            ResultSet rs =insert.executeQuery();
            if(rs.next()){
                int val = rs.getInt("quantity");
                insert = con1.prepareStatement("update sells set quantity =? where mid=? and pharm_id = ?");
                insert.setInt(1, val+qnt);
                insert.setInt(2, mid);
            insert.setInt(3, pharm_id);
            insert.executeUpdate();
            }else{
            
            insert = con1.prepareStatement("insert into sells(mid,pharm_id,quantity) values(?,?,?)");
            insert.setInt(1, mid);
            insert.setInt(2, pharm_id);
            insert.setInt(3, qnt);
            insert.executeUpdate();
            }
        JOptionPane.showMessageDialog(this, "Success insertion");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
        }        
    }//GEN-LAST:event_buttonAddSellsActionPerformed

    private void textSellsPharmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSellsPharmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSellsPharmActionPerformed

    private void billDetailsMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billDetailsMainActionPerformed
        setVisible(false);
        new CheckBill().setVisible(true);
    }//GEN-LAST:event_billDetailsMainActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void buttonEmployeeDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEmployeeDetailsActionPerformed
       setVisible(false);
       new ShowEmployeeDetails().setVisible(true);
    }//GEN-LAST:event_buttonEmployeeDetailsActionPerformed
  ArrayList<String> pharmacyList = new ArrayList<>();
    
    public void PharmacySelect(){
        int c;
      try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy","root","");

            insert = con1.prepareStatement("select name from pharmacy");
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData rss = (ResultSetMetaData) rs.getMetaData();
            c = rss.getColumnCount();
            pharmacyList.clear();
            while(rs.next()){
                pharmacyList.add(rs.getString("name"));
            }
            dropPharmacyName.removeAllItems();
            for(String str:pharmacyList)dropPharmacyName.addItem(str);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
        }
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pharmacy().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BillDetailPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton billDetailsMain;
    private javax.swing.JTable billTable;
    private javax.swing.JButton buttonAddItem;
    private javax.swing.JButton buttonAddSells;
    private javax.swing.JButton buttonCheckOut;
    private javax.swing.JButton buttonEmployeeDetails;
    private javax.swing.JButton buttonMainAddItems;
    private javax.swing.JButton buttonMainPharmacy;
    private javax.swing.JButton buttonMedAdd;
    private javax.swing.JButton buttonMedicine;
    private javax.swing.JButton buttonOkPharmacyName;
    private javax.swing.JButton buttonPatient;
    private javax.swing.JButton buttonPatientAdd;
    private javax.swing.JButton buttonPharmacy;
    private javax.swing.JButton buttonSells;
    private javax.swing.JComboBox<String> dropPharmacyName;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelBillNotFound;
    private javax.swing.JPanel panel10;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JPanel panel6;
    private javax.swing.JPanel panel7;
    private javax.swing.JPanel panel8;
    private javax.swing.JPanel panel9;
    private javax.swing.JTextField patientIdCart;
    private javax.swing.JLabel pharmacyNameTag;
    private javax.swing.JLabel pharmacyNameTag1;
    private javax.swing.JTable tableCart;
    private javax.swing.JTable tableDrugCatalog;
    private javax.swing.JTable tableMedicineSells;
    private javax.swing.JTable tablePharmacySells;
    private javax.swing.JTable tableTotalBill;
    private javax.swing.JTextField textMedExp;
    private javax.swing.JTextField textMedName;
    private javax.swing.JTextField textMedPrice;
    private javax.swing.JLabel textNameBillTotal;
    private javax.swing.JTextField textPatientAddress;
    private javax.swing.JTextField textPatientAge;
    private javax.swing.JTextField textPatientGender;
    private javax.swing.JTextField textPatientPhone;
    private javax.swing.JTextField textPhAddress;
    private javax.swing.JTextField textPhName;
    private javax.swing.JTextField textPhPhone;
    private javax.swing.JLabel textPidBillTotal;
    private javax.swing.JTextField textQuantityDrugCatalog;
    private javax.swing.JTextField textSellsMid;
    private javax.swing.JTextField textSellsPharm;
    private javax.swing.JTextField textSellsQuantity;
    private javax.swing.JLabel textTotalBillTotal;
    private javax.swing.JTextField textpatientName;
    // End of variables declaration//GEN-END:variables
}
