/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacy;

import com.mysql.jdbc.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author A-jay
 */
public class PharmacyData extends javax.swing.JFrame {
Connection con1;
        PreparedStatement insert;
        HashMap<Integer,Integer> set;
    /**
     * Creates new form PharmacyData
     */
        String pharmacyName="";
    private String pass;
    private String user;
    public PharmacyData(String pharmacyName) {
         this();
        //JOptionPane.showMessageDialog(this, pharmacyName);
        this.pharmacyName = pharmacyName;
        set = new HashMap<>();
        DefaultTableModel model = (DefaultTableModel) tableCart.getModel();
            model.setRowCount(0);
            SetPharmacyData();
    }
      public PharmacyData() {
           this.setLocation(500, 250);
        this.setVisible(true);
        user = Singleton.getInstance().getUser();
        pass = Singleton.getInstance().getPass();
        initComponents();
      }
    
    
     public void SetPharmacyData(){
       // String pharmacyName = dropPharmacyName.getSelectedItem().toString();
         pharmacyNameTag.setText(pharmacyName);
          int c;
      try {
            //Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy",user,pass);
            insert = con1.prepareStatement("select * from pharmacy where name=?");
             insert.setString(1, pharmacyName);
             //System.out.println(insert.toString());
            ResultSet rs1 = insert.executeQuery();
            int pharm_id = 0;
            if(rs1.next())pharm_id=rs1.getInt("pharm_id");
            insert = con1.prepareStatement("select medicine.mid,medicine.med_name,medicine.price,sells.quantity from medicine,sells where sells.pharm_id=? and sells.mid = medicine.mid");
            insert.setInt(1, pharm_id);
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData rss = (ResultSetMetaData) rs.getMetaData();
            c = rss.getColumnCount();
            
            DefaultTableModel model = (DefaultTableModel) tableDrugCatalog.getModel();
            model.setRowCount(0);
            
            while(rs.next()){
                Vector v2 = new Vector();
                for(int i=0;i<c;i++){
                    v2.add(rs.getInt("mid"));
                    v2.add(rs.getString("med_name"));
                    v2.add(rs.getInt("price"));
                    v2.add(rs.getInt("quantity"));
                    
                }
                model.addRow(v2);
            }
           
        } /*catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        } */catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDrugCatalog = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCart = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        buttonAddItem = new javax.swing.JButton();
        buttonCheckOut = new javax.swing.JButton();
        patientIdCart = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        pharmacyNameTag = new javax.swing.JLabel();
        textQuantityDrugCatalog = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Select Required Row(1 at a time) Then Add Item");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        tableDrugCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MID", "Med_Name", "Price", "qnt"
            }
        ));
        jScrollPane1.setViewportView(tableDrugCatalog);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 149, 325, 92));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Pharmacy Drug Catalog");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 122, -1, -1));

        tableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MID", "Med_Name", "Price", "qnt"
            }
        ));
        jScrollPane2.setViewportView(tableCart);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 339, 325, 91));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Item in cart");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 312, -1, -1));

        buttonAddItem.setText("Add Item");
        buttonAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddItemActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 259, -1, -1));

        buttonCheckOut.setText("Check Out");
        buttonCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCheckOutActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 465, -1, -1));

        patientIdCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIdCartActionPerformed(evt);
            }
        });
        getContentPane().add(patientIdCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 468, 62, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Enter PID :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 468, -1, -1));

        pharmacyNameTag.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        pharmacyNameTag.setText("Pharmacy Name");
        getContentPane().add(pharmacyNameTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 40, -1, -1));

        textQuantityDrugCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQuantityDrugCatalogActionPerformed(evt);
            }
        });
        getContentPane().add(textQuantityDrugCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 260, 38, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("QNT :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue_background.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, 440, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddItemActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableCart.getModel();
        int row = tableDrugCatalog.getSelectedRow();
        //check for not selected
        int mid = Integer.parseInt(tableDrugCatalog.getModel().getValueAt(row, 0).toString().trim());
        //System.out.println(mid);
        String med_name = tableDrugCatalog.getModel().getValueAt(row, 1).toString();
        int price = Integer.parseInt(tableDrugCatalog.getModel().getValueAt(row, 2).toString());
        int qnt = Integer.parseInt(tableDrugCatalog.getModel().getValueAt(row, 3).toString());
        int drugqnt = Integer.parseInt(textQuantityDrugCatalog.getText().toString());
        if(set.get(mid)!=null){
            int tempqnt = set.get(mid);
            if(tempqnt+drugqnt>qnt){
                JOptionPane.showMessageDialog(this, "Quantity Exceed");
                return;
            }else{
                set.put(mid,tempqnt+drugqnt);
                Vector v = new Vector();
                v.add(mid);
                v.add(med_name);
                v.add(price);
                v.add(drugqnt+tempqnt);
            }
            int c = tableCart.getRowCount();
            for(int i=0;i<c;i++){
                if(Integer.parseInt(tableCart.getModel().getValueAt(i, 0).toString())==mid){
                    tableCart.getModel().setValueAt(tempqnt+drugqnt,i, 3);
                }
            }
        }else{
            if(drugqnt>qnt){
                JOptionPane.showMessageDialog(this, "Quantity Exceed");
                return;
            }
            set.put(mid,drugqnt);
            Vector v = new Vector();
            v.add(mid);
            v.add(med_name);
            v.add(price);
            v.add(drugqnt);
            model.addRow(v);
        }
    }//GEN-LAST:event_buttonAddItemActionPerformed

    private void buttonCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCheckOutActionPerformed
        if(patientIdCart.getText().toString().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Please Enter PID");
            return;
        }
        int pid = Integer.parseInt(patientIdCart.getText().toString().trim());

        int val = tableCart.getRowCount();
        int sum=0;
        for(int i=0;i<val;i++){
            int qnt = Integer.parseInt(tableCart.getModel().getValueAt(i, 3).toString().trim());
            int price = Integer.parseInt(tableCart.getModel().getValueAt(i, 2).toString().trim());
            sum+=qnt*price;
        }

        try {
            //Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy",user,pass);

            //String pharmacyName = dropPharmacyName.getSelectedItem().toString();
            insert = con1.prepareStatement("select * from pharmacy where name=?");
            insert.setString(1, pharmacyName);
            ResultSet rs1 = insert.executeQuery();
            int pharm_id = 0;
            if(rs1.next())pharm_id=rs1.getInt("pharm_id");
            
            long millis=System.currentTimeMillis();
            java.sql.Date curDate=new java.sql.Date(millis);
            insert = con1.prepareStatement("insert into bill(amount,pid,pharm_id,date_out) values(?,?,?,?)");
            //insert.setInt(1, id);
            insert.setInt(1, sum);
            insert.setInt(2, pid);
            insert.setInt(3,pharm_id);
            insert.setDate(4, curDate);
            insert.executeUpdate();

            insert = con1.prepareStatement("select * from bill order by bid desc limit 1");
            ResultSet rs = insert.executeQuery();
            int bid =0;
            if(rs.next()){
                bid = rs.getInt("bid");
            }

            for(int i=0;i<val;i++){
                int qnt = Integer.parseInt(tableCart.getModel().getValueAt(i, 3).toString().trim());
                int mid = Integer.parseInt(tableCart.getModel().getValueAt(i, 0).toString().trim());

                insert = con1.prepareStatement("insert into med_on_bill(bid,mid,quantiy)values(?,?,?)");
                insert.setInt(1, bid);
                insert.setInt(2, mid);
                insert.setInt(3, qnt);
                insert.executeUpdate();
                System.out.print(qnt);
                insert = con1.prepareStatement("update sells set quantity =(select sum(quantity) from sells where mid=? and pharm_id= ?)-? where mid=? and pharm_id =?");
                insert.setInt(1,mid);
                insert.setInt(2,pharm_id);
                insert.setInt(3,qnt);
                insert.setInt(4,mid);
                insert.setInt(5,pharm_id);
                insert.executeUpdate();

            }

            new ExecuteBill(bid,pid).setVisible(true);
            setVisible(false);
            JOptionPane.showMessageDialog(this, "Success Bill");
        } /*catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
        }*/ catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
        }

    }//GEN-LAST:event_buttonCheckOutActionPerformed

    
    private void patientIdCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIdCartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIdCartActionPerformed

    private void textQuantityDrugCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQuantityDrugCatalogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQuantityDrugCatalogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacyData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacyData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacyData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacyData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PharmacyData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddItem;
    private javax.swing.JButton buttonCheckOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField patientIdCart;
    private javax.swing.JLabel pharmacyNameTag;
    private javax.swing.JTable tableCart;
    private javax.swing.JTable tableDrugCatalog;
    private javax.swing.JTextField textQuantityDrugCatalog;
    // End of variables declaration//GEN-END:variables
}
