/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacy;
import com.mysql.jdbc.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author A-jay
 */
public class SelectPharmacy extends javax.swing.JFrame {
 Connection con1;
        PreparedStatement insert;
    private final String pass;
    private final String user;
    /**
     * Creates new form SelectPharmacy
     */
    public SelectPharmacy() {
         this.setLocation(500, 250);
        this.setVisible(true);
        initComponents();
        user = Singleton.getInstance().getUser();
        pass = Singleton.getInstance().getPass();
        PharmacySelect();
    }
ArrayList<String> pharmacyList = new ArrayList<>();
    
    public void PharmacySelect(){
        int c;
      try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy",user,pass);

            insert = con1.prepareStatement("select name from pharmacy");
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData rss = (ResultSetMetaData) rs.getMetaData();
            c = rss.getColumnCount();
            pharmacyList.clear();
            while(rs.next()){
                pharmacyList.add(rs.getString("name"));
            }
            dropPharmacyName.removeAllItems();
            for(String str:pharmacyList)dropPharmacyName.addItem(str);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
        }
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dropPharmacyName = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        buttonOkPharmacyName = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropPharmacyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropPharmacyNameActionPerformed(evt);
            }
        });
        getContentPane().add(dropPharmacyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 157, 161, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Pharmacy Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 129, -1, -1));

        buttonOkPharmacyName.setText("Ok");
        buttonOkPharmacyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkPharmacyNameActionPerformed(evt);
            }
        });
        getContentPane().add(buttonOkPharmacyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 221, -1, -1));

        jLabel29.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel29.setText("Select Pharmacy");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 56, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue_background.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 410, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropPharmacyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropPharmacyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropPharmacyNameActionPerformed

    private void buttonOkPharmacyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkPharmacyNameActionPerformed

        if(dropPharmacyName.getSelectedItem()!=null){
            new PharmacyData(dropPharmacyName.getSelectedItem().toString()).setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_buttonOkPharmacyNameActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectPharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectPharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectPharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectPharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectPharmacy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOkPharmacyName;
    private javax.swing.JComboBox<String> dropPharmacyName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
