/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacy;

import com.mysql.jdbc.ResultSetMetaData;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A-jay
 */
public class ShowEmployeeDetails extends javax.swing.JFrame {

    private Connection con1;
    private PreparedStatement insert;
    private final String pass;
    private final String user;

    /**
     * Creates new form CheckBill
     */
    public ShowEmployeeDetails() {
        this.setLocation(500, 250);
        this.setVisible(true);
        initComponents();
        user = Singleton.getInstance().getUser();
        pass = Singleton.getInstance().getPass();
        labelBillNotFound.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchCheckBill = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        labelBillNotFound = new javax.swing.JLabel();
        textPharmId = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(1500);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchCheckBill.setText("Search");
        searchCheckBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCheckBillActionPerformed(evt);
            }
        });
        getContentPane().add(searchCheckBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Name", "Salary", "Phone no", "Joining", "Address"
            }
        ));
        jScrollPane5.setViewportView(employeeTable);
        if (employeeTable.getColumnModel().getColumnCount() > 0) {
            employeeTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 474, 63));

        labelBillNotFound.setForeground(new java.awt.Color(255, 0, 51));
        labelBillNotFound.setText("Wrong Pharmacy id Entered");
        getContentPane().add(labelBillNotFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        textPharmId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPharmIdActionPerformed(evt);
            }
        });
        getContentPane().add(textPharmId, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 142, 74, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel32.setText("pharm_id:");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel33.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel33.setText("Employees Details");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 41, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue_background.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 500, 370));

        setBounds(0, 0, 512, 376);
    }// </editor-fold>//GEN-END:initComponents

    private void textPharmIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPharmIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPharmIdActionPerformed

    private void searchCheckBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCheckBillActionPerformed
            String str = textPharmId.getText().toString().trim();
            int pharm_id = Integer.parseInt(str);
            EmployeeDetail(pharm_id);
            
    }//GEN-LAST:event_searchCheckBillActionPerformed

    
    public void EmployeeDetail(int pharm_id){
        int c;
      try {
            //Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/pharmacy",user,pass);
            
            insert = con1.prepareStatement("select emp_name,salary,address,joining_date,phone_no from employee where pharm_id=? ");
            insert.setInt(1, pharm_id);
            
            ResultSet rs = insert.executeQuery();
           
            DefaultTableModel model = (DefaultTableModel) employeeTable.getModel();
            model.setRowCount(0);
            if(rs.next()){
                Vector v2 = new Vector();
                    v2.add(rs.getString("emp_name"));
                    v2.add(rs.getInt("salary"));
                    v2.add(rs.getString("phone_no"));
                    v2.add(rs.getDate("joining_date"));
                    v2.add(rs.getString("address"));
                model.addRow(v2);
                labelBillNotFound.setVisible(false);
            }else{
                labelBillNotFound.setVisible(true);
            }
            while(rs.next()){
                Vector v2 = new Vector();
                    v2.add(rs.getString("emp_name"));
                    v2.add(rs.getInt("salary"));
                    v2.add(rs.getString("phone_no"));
                    v2.add(rs.getDate("joining_date"));
                    v2.add(rs.getString("address"));
                model.addRow(v2);
                labelBillNotFound.setVisible(false);
            }
           
        }/* catch (ClassNotFoundException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
        } */catch (SQLException ex) {
            Logger.getLogger(Pharmacy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.toString());
       
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowEmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowEmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowEmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowEmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowEmployeeDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable employeeTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelBillNotFound;
    private javax.swing.JButton searchCheckBill;
    private javax.swing.JTextField textPharmId;
    // End of variables declaration//GEN-END:variables
}
